mod build;
mod lockfile;
mod project_compiler;

use std::collections::HashSet;
use std::fmt::{Debug, Formatter};
use std::ops::ControlFlow;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use clap::Parser;
use forge::args::setup;
use forge::opts::{Forge, ForgeSubcommand};
use foundry_common::errors::convert_solar_errors;
use foundry_common::version::{LONG_VERSION, SHORT_VERSION};
use foundry_compilers::artifacts::{SolcLanguage, Sources};
use foundry_compilers::error::SolcError;
use foundry_compilers::multi::{MultiCompiler, MultiCompilerInput};
use foundry_compilers::project::Preprocessor;
use foundry_compilers::solc::SolcCompiler;
use foundry_compilers::{Compiler, ProjectPathsConfig, SourceParser};
use solar::sema::Gcx;

#[derive(Parser)]
#[command(
    name = "reforge",
    version = SHORT_VERSION,
    long_version = LONG_VERSION,
    about = "A tool for combining with Forge with macro expansions in Solidity.",
)]
pub struct Reforge {
    #[arg(
        long,
        help = "Expand macros in the input files."
    )]
    pub expand_macros: bool,
    #[command(flatten)]
    pub forge: Forge,
}

/// The data passed to implementations of the `Preprocessor` trait.
#[derive(Debug)]
pub struct PreprocessingData<'pre> {
    /// The source files being compiled
    pub input: &'pre mut Sources,
    /// The root of the project being compiled.
    pub root_dir: &'pre Path,
    /// Where to find the sources
    pub src_dir: &'pre Path,
    /// Mocks generated by foundry/forge.
    pub mocks: &'pre mut HashSet<PathBuf>,
}

/// A collection of macro rules which will be executed as a `Preprocessor`
#[derive(Default, Clone)]
pub struct MacroRules {
    pub rules: Vec<fn(&Gcx, &mut PreprocessingData<'_>) -> foundry_compilers::error::Result<()>>,
    pub(crate) preprocessed_sources: Arc<Mutex<Option<Sources>>>,
}

impl Debug for MacroRules {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MacroRules")
            .field("rules", &"<functions>")
            .finish()
    }
}

impl MacroRules {
    /// Runs the CLI. This should be used by downstream users as the main entry point of their
    /// program.
    pub fn run(self) -> eyre::Result<()> {
        setup()?;
        let args = Reforge::parse();
        args.forge.global.init()?;

        if args.expand_macros {
            if self.rules.is_empty() {
                tracing::info!("No macros rules present, skipping macro expansion.");
                println!("No macros rules present, skipping macro expansion.");
            } else if let ForgeSubcommand::Build(build_args) = args.forge.cmd {
                if build_args.build.dynamic_test_linking {
                    tracing::warn!(
                        "Dynamic linking is not supported with macros expansion, skipping."
                    );
                    println!("Dynamic linking is not supported with macros expansion, skipping.");
                }
                return args.forge.global.block_on(build::build(build_args, self));
            }
        }
        forge::args::run_command(args.forge)
    }
}

impl Preprocessor<SolcCompiler> for MacroRules {
    fn preprocess(
        &self,
        _compiler: &SolcCompiler,
        input: &mut <SolcCompiler as Compiler>::Input,
        paths: &ProjectPathsConfig<<SolcCompiler as Compiler>::Language>,
        mocks: &mut HashSet<PathBuf>,
    ) -> foundry_compilers::error::Result<()> {
        let mut compiler =
            foundry_compilers::resolver::parse::SolParser::new(paths.with_language_ref())
                .into_compiler();
        compiler.enter_mut(|compiler| -> foundry_compilers::error::Result<()> {
            let mut pcx = compiler.parse();

            // Add the sources into the context.
            // Include all sources in the source map so as to not re-load them from disk, but only
            // parse and preprocess tests and scripts.
            let sources = &mut input.input.sources;
            for (path, source) in sources.iter() {
                if let Ok(src_file) = compiler
                    .sess()
                    .source_map()
                    .new_source_file(path.clone(), source.content.as_str())
                {
                    pcx.add_file(src_file);
                }
            }

            // Parse and preprocess.
            pcx.parse();
            let ControlFlow::Continue(()) = compiler
                .lower_asts()
                .map_err(|_| SolcError::msg("Error lowing AST to HIR during pre-processing"))?
            else {
                return Ok(());
            };
            let mut prepocessing_data = PreprocessingData {
                input: &mut input.input.sources,
                root_dir: &paths.root,
                src_dir: &paths.paths_relative().sources,
                mocks,
            };
            let gcx = compiler.gcx();
            for rule in &self.rules {
                rule(&gcx, &mut prepocessing_data)?;
            }
            *self.preprocessed_sources.lock().unwrap() = Some(prepocessing_data.input.clone());
            Ok(())
        })?;

        // Solar diagnostics during preprocessing are intentionally ignored: the source passed to
        // Solar is the original, unmodified code, so references to symbols that macros will inject
        // are expected to be unresolved at this stage.
        let _ = convert_solar_errors(compiler.dcx());

        Ok(())
    }
}

impl Preprocessor<MultiCompiler> for MacroRules {
    fn preprocess(
        &self,
        compiler: &MultiCompiler,
        input: &mut <MultiCompiler as Compiler>::Input,
        paths: &ProjectPathsConfig<<MultiCompiler as Compiler>::Language>,
        mocks: &mut HashSet<PathBuf>,
    ) -> foundry_compilers::error::Result<()> {
        // Preprocess only Solc compilers.
        let MultiCompilerInput::Solc(input) = input else {
            return Ok(());
        };

        let Some(solc) = &compiler.solc else {
            return Ok(());
        };

        let paths = paths.clone().with_language::<SolcLanguage>();
        self.preprocess(solc, input, &paths, mocks)
    }
}
