mod build;
pub mod display;
mod lockfile;
mod project_compiler;
mod test;
pub mod testing;

use std::collections::HashSet;
use std::fmt::{Debug, Formatter};
use std::ops::ControlFlow;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use clap::Parser;
use forge::args::setup;
use forge::cmd::build::BuildArgs;
use forge::opts::{Forge, ForgeSubcommand};
use foundry_cli::utils::LoadConfig;
use foundry_common::errors::convert_solar_errors;
use foundry_common::version::{LONG_VERSION, SHORT_VERSION};
use foundry_compilers::artifacts::{SolcLanguage, Sources};
use foundry_compilers::multi::{MultiCompiler, MultiCompilerInput};
use foundry_compilers::project::Preprocessor;
use foundry_compilers::solc::SolcCompiler;
use foundry_compilers::{Compiler, ProjectPathsConfig, SourceParser};
use solar::sema::Gcx;

#[derive(Parser)]
#[command(
    name = "reforge",
    version = SHORT_VERSION,
    long_version = LONG_VERSION,
    about = "A tool for combining with Forge with macro expansions in Solidity.",
)]
pub struct Reforge {
    #[arg(long, help = "Disable macro expansion.")]
    pub disable_macros: bool,
    /// Print macro-expanded sources whose paths (relative to the build root)
    /// match this glob pattern, then exit. Only supported with the `build`
    /// subcommand.
    #[arg(long, value_name = "GLOB")]
    pub display: Option<String>,
    #[command(flatten)]
    pub forge: Forge,
}

/// A macro rule function: takes the global compiler context and mutable preprocessing data,
/// and returns a result.
pub type Macro =
    fn(ctx: &Gcx, data: &mut PreprocessingData<'_>) -> foundry_compilers::error::Result<()>;

/// The data passed to implementations of the `Preprocessor` trait.
#[derive(Debug)]
pub struct PreprocessingData<'pre> {
    /// The source files being compiled
    pub input: &'pre mut Sources,
    /// The root of the project being compiled.
    pub root_dir: &'pre Path,
    /// Where to find the sources
    pub src_dir: &'pre Path,
    /// Mocks generated by foundry/forge.
    pub mocks: &'pre mut HashSet<PathBuf>,
    /// Byte offset adjustments accumulated by macro rules that change source text length.
    /// Each entry is `(path, original_offset, delta)`. Rules that use HIR spans should call
    /// [`PreprocessingData::adjusted_offset`] to compensate for prior insertions/deletions.
    pub offset_adjustments: Vec<(PathBuf, usize, isize)>,
}

impl PreprocessingData<'_> {
    /// Returns the current offset in `path` corresponding to `original_offset` from the HIR,
    /// accounting for all length-changing edits recorded by previous macro rules. This is done
    /// by summing all offset deltas affecting the source code prior to the input `original_offset`.
    pub fn adjusted_offset(&self, path: &Path, original_offset: usize) -> usize {
        let delta: isize = self
            .offset_adjustments
            .iter()
            .filter(|(p, edit_offset, _)| p == path && *edit_offset <= original_offset)
            .map(|(_, _, delta)| delta)
            .sum();
        (original_offset as isize + delta) as usize
    }

    /// Inserts `text` into the source file at `path` at the position corresponding to
    /// `original_offset` in the original, unmodified source, and records the edit in
    /// [`PreprocessingData::offset_adjustments`] so that subsequent macro rules remain correct.
    ///
    /// `original_offset` must be a byte offset derived from a Solar HIR span (i.e. relative to
    /// the unmodified source). The method translates it to the current position in the
    /// already-modified text before performing the insertion.
    pub fn insert(
        &mut self,
        path: impl AsRef<Path>,
        original_offset: usize,
        text: impl AsRef<str>,
    ) {
        let path = path.as_ref();
        let adjusted = self.adjusted_offset(path, original_offset);
        let src = self.input.get_mut(path).unwrap();
        let content = Arc::make_mut(&mut src.content);
        content.insert_str(adjusted, text.as_ref());
        self.offset_adjustments.push((
            path.to_path_buf(),
            original_offset,
            text.as_ref().len() as isize,
        ));
    }

    /// Replaces the source bytes at `original_range` (in the original, unmodified file) with
    /// `text`, and records the resulting length delta in `offset_adjustments` so that subsequent
    /// calls using offsets derived from the original source remain correct.
    ///
    /// Both range endpoints are translated through any previously recorded adjustments before the
    /// replacement is applied, so overlapping or out-of-order edits to the same file are handled
    /// correctly. Does nothing if `original_range` is empty or inverted.
    pub fn replace(
        &mut self,
        path: impl AsRef<Path>,
        original_range: std::ops::Range<usize>,
        text: impl AsRef<str>,
    ) {
        let path = path.as_ref();
        if original_range.end <= original_range.start {
            return;
        }
        let adjusted_start = self.adjusted_offset(path, original_range.start);
        let adjusted_end = self.adjusted_offset(path, original_range.end);
        let src = self.input.get_mut(path).unwrap();
        let content = Arc::make_mut(&mut src.content);
        content.replace_range(adjusted_start..adjusted_end, text.as_ref());
        let delta =
            text.as_ref().len() as isize - (original_range.end - original_range.start) as isize;
        self.offset_adjustments
            .push((path.to_path_buf(), original_range.start, delta));
    }
}

/// A collection of macro rules which will be executed as a `Preprocessor`
#[derive(Default, Clone)]
pub struct MacroRules {
    pub rules: Vec<Macro>,
    pub(crate) preprocessed_sources: Arc<Mutex<Option<Sources>>>,
}

impl Debug for MacroRules {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MacroRules")
            .field("rules", &"<functions>")
            .finish()
    }
}

impl MacroRules {
    /// Runs the CLI. This should be used by downstream users as the main entry point of their
    /// program.
    pub fn run(self) -> eyre::Result<()> {
        setup()?;
        let args = Reforge::parse();
        args.forge.global.init()?;

        if let Some(glob) = args.display {
            let ForgeSubcommand::Build(build_args) = args.forge.cmd else {
                panic!("--display is only supported with the `build` subcommand");
            };
            let (root, sources) = self.expand_for_display(build_args)?;
            return display::display_sources(&root, &glob, &sources);
        }

        if !args.disable_macros {
            if self.rules.is_empty() {
                tracing::info!("No macros rules present, skipping macro expansion.");
                println!("No macros rules present, skipping macro expansion.");
            } else if let ForgeSubcommand::Build(build_args) = args.forge.cmd {
                if build_args.build.dynamic_test_linking {
                    tracing::warn!(
                        "Dynamic linking is not supported with macros expansion, skipping."
                    );
                    println!("Dynamic linking is not supported with macros expansion, skipping.");
                }
                return args.forge.global.block_on(build::build(build_args, self));
            } else if let ForgeSubcommand::Test(test_args) = args.forge.cmd {
                return args.forge.global.block_on(test::test(test_args, self));
            }
        }
        forge::args::run_command(args.forge)
    }

    fn expand_for_display(&self, build_args: BuildArgs) -> eyre::Result<(PathBuf, Sources)> {
        let config = build_args.load_config()?;
        let project = config.project()?;
        let root = project.root().to_path_buf();
        let paths = project.paths.clone().with_language::<SolcLanguage>();
        let sources = testing::expand_macros(&root, Some(&paths), &self.rules)?;
        Ok((root, sources))
    }
}

impl Preprocessor<SolcCompiler> for MacroRules {
    fn preprocess(
        &self,
        _compiler: &SolcCompiler,
        input: &mut <SolcCompiler as Compiler>::Input,
        paths: &ProjectPathsConfig<<SolcCompiler as Compiler>::Language>,
        mocks: &mut HashSet<PathBuf>,
    ) -> foundry_compilers::error::Result<()> {
        let mut compiler =
            foundry_compilers::resolver::parse::SolParser::new(paths.with_language_ref())
                .into_compiler();
        compiler.enter_mut(|compiler| -> foundry_compilers::error::Result<()> {
            let mut pcx = compiler.parse();

            // Add the sources into the context.
            // Include all sources in the source map so as to not re-load them from disk, but only
            // parse and preprocess tests and scripts.
            let sources = &mut input.input.sources;
            for (path, source) in sources.iter() {
                if let Ok(src_file) = compiler
                    .sess()
                    .source_map()
                    .new_source_file(path.clone(), source.content.as_str())
                {
                    pcx.add_file(src_file);
                }
            }

            // Parse and preprocess.
            pcx.parse();
            let Ok(ControlFlow::Continue(())) = compiler.lower_asts() else {
                return Ok(());
            };
            let mut prepocessing_data = PreprocessingData {
                input: &mut input.input.sources,
                root_dir: &paths.root,
                src_dir: &paths.paths_relative().sources,
                mocks,
                offset_adjustments: Vec::new(),
            };
            let gcx = compiler.gcx();
            for rule in &self.rules {
                rule(&gcx, &mut prepocessing_data)?;
            }
            *self.preprocessed_sources.lock().unwrap() = Some(prepocessing_data.input.clone());
            Ok(())
        })?;

        // Solar diagnostics during preprocessing are intentionally ignored: the source passed to
        // Solar is the original, unmodified code, so references to symbols that macros will inject
        // are expected to be unresolved at this stage.
        let _ = convert_solar_errors(compiler.dcx());

        Ok(())
    }
}

impl Preprocessor<MultiCompiler> for MacroRules {
    fn preprocess(
        &self,
        compiler: &MultiCompiler,
        input: &mut <MultiCompiler as Compiler>::Input,
        paths: &ProjectPathsConfig<<MultiCompiler as Compiler>::Language>,
        mocks: &mut HashSet<PathBuf>,
    ) -> foundry_compilers::error::Result<()> {
        // Preprocess only Solc compilers.
        let MultiCompilerInput::Solc(input) = input else {
            return Ok(());
        };

        let Some(solc) = &compiler.solc else {
            return Ok(());
        };

        let paths = paths.clone().with_language::<SolcLanguage>();
        self.preprocess(solc, input, &paths, mocks)
    }
}

/// Returns the comment immediately preceding the given HIR item, if any.
///
/// Walks backward from `span` in the source text and collects contiguous non-empty lines
/// that form a comment block (`//` or `/* ... */`). Returns `None` if the preceding
/// non-whitespace content is not a comment, or if the item's source is not in `data.input`.
pub fn get_comment(
    ctx: &Gcx,
    source_id: solar::sema::hir::SourceId,
    span: solar::interface::Span,
    data: &PreprocessingData<'_>,
) -> Option<String> {
    let source = ctx.sources.get(source_id)?;
    let path = source.file.name.as_real()?;
    let source_text = data.input.get(path)?.content.as_str();
    let original_offset = (span.lo().0 - source.file.start_pos.0) as usize;
    let adjusted = data.adjusted_offset(path, original_offset);
    // Walk back to the start of the line
    let line_start = source_text[..adjusted]
        .rfind('\n')
        .map(|i| i + 1)
        .unwrap_or(0);
    let before = &source_text[..line_start];
    let mut comment_block = String::new();
    // Walk backward over whitespace/newlines to find the preceding line(s)
    for l in before.lines().rev() {
        if l.trim().is_empty() {
            break;
        }
        comment_block.insert_str(0, l);
        if l.trim().starts_with("/*") {
            break;
        }
    }
    let trimmed = comment_block.trim_start();
    if trimmed.starts_with("//") || trimmed.starts_with("/*") {
        Some(comment_block)
    } else {
        None
    }
}
